Repository 111590039/OOPL-infinitode, pull requests merged in 2024-06, with the labels that each got.

#25 more enemy and restart wave and more map
  Resources/enemy_Jet.bmp
  Source/Library/enemy.cpp
  Source/Library/enemy.h
  Source/Library/gamemap.cpp
  Source/Library/wave.cpp
  Source/Library/wave.h
  Source/Map/level10.map
  Source/Map/level11.map
  Source/Map/level12.map
  Source/Map/level13.map
  Source/Map/level14.map
  Source/Map/level15.map
  Source/Map/level16.map
  Source/Map/level17.map
  Source/Map/level2.map
  Source/Map/level3.map
  Source/Map/level4.map
  Source/Map/level5.map
  Source/Map/level6.map
  Source/Map/level7.map
  Source/Map/level8.map
  Source/Map/level9.map
Labels: documentation, enhancement

#26 More tower3
  Resources/preview1.bmp
  Resources/selectlevel.bmp
  Source/Game/Settings.map
  Source/Game/mygame.h
  Source/Game/mygame_initialize.cpp
  Source/Game/mygame_run.cpp
  Source/Library/gamemap.cpp
  Source/Library/gamemap.h
  Source/Library/tower/freezing.cpp
  Source/Library/tower/freezing.h
  Source/Map/level1.map
Labels: enhancement

#28 EnemyPath & SkipWave
  Source/Library/enemy.cpp
  Source/Library/gamemap.cpp
  Source/Library/wave.cpp
  Source/Library/wave.h
  Source/Map/level10.map
  Source/Map/level2.map
  Source/Map/level3.map
  Source/Map/level4.map
  Source/Map/level5.map
  Source/Map/level6.map
  Source/Map/level7.map
  Source/Map/level8.map
  Source/Map/level9.map
Labels: bug, documentation, enhancement

#29 finalVer
  Source/Game/mygame.h
  Source/Game/mygame_initialize.cpp
  Source/Game/mygame_run.cpp
  Source/Library/enemy.cpp
  Source/Library/gamemap.cpp
  Source/Library/gamemap.h
  Source/Map/level11.map
  Source/Map/level12.map
  Source/Map/level13.map
  Source/Map/level14.map
  Source/Map/level15.map
  Source/Map/level16.map
  Source/Map/level17.map
Labels: enhancement

#30 finalVer
  Source/Game/mygame_initialize.cpp
  Source/Library/enemy.cpp
  Source/Library/gamemap.cpp
  Source/Map/level10.map
  Source/Map/level11.map
  Source/Map/level12.map
  Source/Map/level13.map
  Source/Map/level14.map
  Source/Map/level15.map
  Source/Map/level16.map
  Source/Map/level17.map
  Source/Map/level2.map
  Source/Map/level3.map
  Source/Map/level4.map
  Source/Map/level5.map
  Source/Map/level6.map
  Source/Map/level7.map
  Source/Map/level8.map
  Source/Map/level9.map
Labels: documentation, enhancement
